# Generated by Django 5.0.9 on 2026-09-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0008_documentappearance_and_more"),
        ("patients", "0003_patient_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                help_text="Convenio o aseguradora que cubre al paciente (RF-CFG-04). Vacío = paciente particular.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="configuration.agreement",
            ),
        ),
    ]
