# Generated by Django 6.0.6 on 2026-07-07 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('patients', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOptIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opted_in_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='registro_recepcion', help_text='Canal por el que el paciente dio su consentimiento.', max_length=50)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_optins', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Opt-in de WhatsApp',
                'verbose_name_plural': 'Opt-ins de WhatsApp',
            },
        ),
    ]
