# Generated by Django 5.0.9 on 2026-09-23 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_tenant_funcionalidades"),
        ("whatsapp", "0002_whatsappoptin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionWhatsApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="Identificador de número (Meta)",
                    ),
                ),
                (
                    "numero_visible",
                    models.CharField(
                        blank=True,
                        help_text="Con código de país, p. ej. +593999111222.",
                        max_length=30,
                        verbose_name="Número tal como lo ve el paciente",
                    ),
                ),
                ("access_token_cifrado", models.TextField(blank=True, default="")),
                (
                    "plantilla_recordatorio",
                    models.CharField(
                        blank=True,
                        default="recordatorio_cita",
                        help_text="Nombre de la plantilla aprobada en Meta.",
                        max_length=80,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=False,
                        help_text="Mientras esté apagado no sale ningún mensaje automático.",
                    ),
                ),
                ("comprobado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de WhatsApp",
                "verbose_name_plural": "Configuraciones de WhatsApp",
            },
        ),
        migrations.AddConstraint(
            model_name="configuracionwhatsapp",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="una_configuracion_whatsapp_por_clinica"
            ),
        ),
    ]
