# Generated by Django 5.0.9 on 2026-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_platform_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="funcionalidades",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Qué módulos tiene esta clínica. El catálogo está en apps/common/funcionalidades.py. Apagar uno NO borra sus datos: deja de verse y de poder tocarse.",
                verbose_name="Funcionalidades contratadas",
            ),
        ),
    ]
