# Generated by Django 5.2.17 on 2026-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_tenant_funcionalidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="modulos_clinica",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Módulos que la clínica decide usar",
            ),
        ),
    ]
