# Generated by Django 6.0.6 on 2026-07-03 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('configuration', '0002_initial'),
        ('patients', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_color', models.CharField(default='#3b82f6', help_text='Color hex para distinguirlo en la agenda.', max_length=7)),
                ('google_calendar_token', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='doctors', to='specialties.specialty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('completed', 'Completada'), ('no_show', 'No asistió')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='configuration.treatment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='agenda.doctor')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'indexes': [models.Index(fields=['tenant', 'doctor', 'scheduled_start'], name='agenda_appo_tenant__b5db2c_idx'), models.Index(fields=['tenant', 'scheduled_start'], name='agenda_appo_tenant__8286f0_idx'), models.Index(fields=['status'], name='agenda_appo_status_8e291c_idx')],
            },
        ),
    ]
