# Generated by Django 5.0.9 on 2026-09-24 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0004_doctor_signature"),
        ("common", "0003_tenant_funcionalidades"),
        ("patients", "0004_patient_agreement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeConsultorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("texto", models.TextField()),
                ("respuesta", models.TextField(blank=True)),
                ("respondido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_consultorio",
                        to="patients.patient",
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje al consultorio",
                "verbose_name_plural": "Mensajes al consultorio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudCita",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_preferida", models.DateField()),
                (
                    "franja",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana"),
                            ("tarde", "Tarde"),
                            ("cualquiera", "Cualquier hora"),
                        ],
                        default="cualquiera",
                        max_length=12,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("agendada", "Agendada"),
                            ("rechazada", "No se pudo agendar"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("respuesta", models.CharField(blank=True, max_length=300)),
                ("atendida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agenda.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_cita",
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de cita desde la app",
                "verbose_name_plural": "Solicitudes de cita desde la app",
                "ordering": ["-created_at"],
            },
        ),
    ]
