# Generated by Django 5.0.9 on 2026-09-22 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_platform_v2"),
        ("patients", "0004_patient_agreement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Logro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Lo que el paciente lee en la app.",
                        max_length=200,
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        default="estrella",
                        help_text="estrella · diente · racha · corazon · escudo · regalo",
                        max_length=30,
                    ),
                ),
                (
                    "beneficio",
                    models.CharField(
                        blank=True,
                        help_text="Lo que gana. Informativo: no se aplica solo al presupuesto.",
                        max_length=200,
                    ),
                ),
                (
                    "regla",
                    models.CharField(
                        choices=[
                            ("manual", "Lo otorga una persona"),
                            ("asistencia_mensual", "Asistió a sus citas del mes"),
                            ("al_dia_pagos", "Sin cuotas vencidas"),
                        ],
                        default="manual",
                        max_length=25,
                    ),
                ),
                ("meses_requeridos", models.PositiveSmallIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="LogroDePaciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("otorgado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo",
                    models.DateField(
                        blank=True,
                        help_text="Primer día del mes que se premia. Nulo si es manual.",
                        null=True,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                (
                    "logro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concesiones",
                        to="logros.logro",
                    ),
                ),
                (
                    "otorgado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logros_otorgados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros",
                        to="patients.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro de paciente",
                "verbose_name_plural": "Logros de pacientes",
                "ordering": ["-otorgado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="logro",
            constraint=models.UniqueConstraint(
                fields=("tenant", "nombre"), name="logro_unico_por_clinica"
            ),
        ),
        migrations.AddConstraint(
            model_name="logrodepaciente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("periodo__isnull", False)),
                fields=("patient", "logro", "periodo"),
                name="un_logro_por_paciente_y_periodo",
            ),
        ),
    ]
