# Generated by Django 6.0.6 on 2026-07-06 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('common', '0001_initial'),
        ('configuration', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Historia clínica',
                'verbose_name_plural': 'Historias clínicas',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth_fdi_code', models.CharField(blank=True, help_text="Código FDI (ej. '26'); vacío si es diagnóstico general.", max_length=2)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='agenda.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='agenda.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Plan de tratamiento',
                'verbose_name_plural': 'Planes de tratamiento',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tooth_fdi_code', models.CharField(blank=True, max_length=2)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En progreso'), ('done', 'Realizado')], default='planned', max_length=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.treatment')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.treatmentplan')),
            ],
            options={
                'verbose_name': 'Ítem de plan de tratamiento',
                'verbose_name_plural': 'Ítems de plan de tratamiento',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('clinical_note', 'Nota clínica'), ('prescription', 'Receta'), ('care_instruction', 'Indicación de cuidado')], default='clinical_note', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('visible_to_patient', models.BooleanField(default=False, help_text='Si es True, el paciente lo ve en la app (RF-APP-03).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='agenda.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', to='agenda.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'indexes': [models.Index(fields=['patient', 'date'], name='clinical_ev_patient_7671fb_idx'), models.Index(fields=['patient', 'type', 'visible_to_patient'], name='clinical_ev_patient_6ad850_idx')],
            },
        ),
    ]
