# Generated by Django 6.0.6 on 2026-07-06 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinical', '0001_initial'),
        ('common', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdontogramState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', help_text='Color hex para la UI.', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Estado de odontograma',
                'verbose_name_plural': 'Estados de odontograma',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth_fdi_code', models.CharField(help_text='Código FDI: 11-48 (permanente), 51-85 (temporal).', max_length=2)),
                ('surface', models.CharField(choices=[('whole', 'Toda la pieza'), ('vestibular', 'Vestibular'), ('palatal_lingual', 'Palatina/Lingual'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('occlusal', 'Oclusal')], default='whole', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooth_records', to='agenda.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='patients.patient')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooth_records', to='clinical.odontogramstate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
                ('treatment_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooth_records', to='clinical.treatmentplanitem')),
            ],
            options={
                'verbose_name': 'Registro de pieza dental',
                'verbose_name_plural': 'Registros de piezas dentales',
            },
        ),
        migrations.AddConstraint(
            model_name='odontogramstate',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_odontogram_state_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='toothrecord',
            index=models.Index(fields=['patient', 'tooth_fdi_code', 'surface'], name='clinical_to_patient_12eb96_idx'),
        ),
        migrations.AddIndex(
            model_name='toothrecord',
            index=models.Index(fields=['patient', '-created_at'], name='clinical_to_patient_00aef7_idx'),
        ),
    ]
