# Generated by Django 6.0.6 on 2026-07-06 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_odontogramstate_toothrecord_and_more'),
        ('common', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformedConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Consentimiento informado', max_length=200)),
                ('body_text', models.TextField(help_text='Texto del consentimiento que el paciente acepta.')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='clinical/consents/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='clinical/signatures/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='clinical.treatmentplan')),
            ],
            options={
                'verbose_name': 'Consentimiento informado',
                'verbose_name_plural': 'Consentimientos informados',
            },
        ),
        migrations.CreateModel(
            name='RadiographPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth_fdi_code', models.CharField(blank=True, max_length=2)),
                ('file', models.FileField(upload_to='clinical/radiographs/')),
                ('type', models.CharField(choices=[('radiograph', 'Radiografía'), ('photo', 'Fotografía')], default='radiograph', max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiographs', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiografía / Fotografía',
                'verbose_name_plural': 'Radiografías / Fotografías',
            },
        ),
    ]
