# Generated by Django 6.0.6 on 2026-07-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinical', '0003_informedconsent_radiographphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='agenda.doctor'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Nulo si registró un usuario clínico sin perfil de doctor (admin/auxiliar).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evolutions', to='agenda.doctor'),
        ),
        migrations.AlterField(
            model_name='toothrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tooth_records', to='agenda.doctor'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='agenda.doctor'),
        ),
    ]
