# Generated by Django 6.0.6 on 2026-07-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_diagnosis_doctor_alter_evolution_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la evolución (doctor, admin o auxiliar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
