# Generated by Django 5.0.9 on 2026-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_seed_cie10'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrequest',
            name='justification',
            field=models.TextField(blank=True, help_text='Motivo o justificación clínica.'),
        ),
        migrations.AddField(
            model_name='examrequest',
            name='observations',
            field=models.TextField(blank=True, help_text='Observaciones adicionales (opcional).'),
        ),
        migrations.AddField(
            model_name='examrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente')], default='normal', max_length=10),
        ),
    ]
