# Generated by Django 5.0.9 on 2026-07-22 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_examrequest_justification_examrequest_observations_and_more'),
        ('common', '0002_platform_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informedconsent',
            name='alternatives',
            field=models.TextField(blank=True, help_text='Alternativas terapéuticas.'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='benefits',
            field=models.TextField(blank=True, help_text='Beneficios.'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='observations',
            field=models.TextField(blank=True, help_text='Observaciones (opcional).'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='procedure',
            field=models.TextField(blank=True, help_text='Descripción del procedimiento.'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='risks',
            field=models.TextField(blank=True, help_text='Riesgos y posibles complicaciones.'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de firma'), ('signed', 'Firmado'), ('void', 'Anulado')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='ConsentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinical.informedconsent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.CharField(choices=[('extraccion', 'Extracción dental'), ('endodoncia', 'Endodoncia'), ('restauracion', 'Restauración'), ('profilaxis', 'Profilaxis'), ('cirugia', 'Cirugía oral'), ('implante', 'Implante'), ('protesis', 'Prótesis'), ('ortodoncia', 'Ortodoncia'), ('otro', 'Otro')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('procedure_text', models.TextField(blank=True, help_text='Descripción del procedimiento.')),
                ('benefits', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('alternatives', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True, help_text='Declaración de aceptación / cuerpo.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Plantilla de consentimiento',
                'verbose_name_plural': 'Plantillas de consentimiento',
                'ordering': ['procedure', 'title'],
            },
        ),
    ]
