# Generated by Django 5.0.9 on 2026-07-30 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_set_signed_status'),
        ('common', '0002_platform_v2'),
        ('patients', '0003_patient_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodontalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Fecha de la exploración.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodontal_exams', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Exploración periodontal',
                'verbose_name_plural': 'Exploraciones periodontales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodontalTooth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth_code', models.CharField(help_text='Código FDI, p. ej. 16.', max_length=2)),
                ('is_present', models.BooleanField(default=True, help_text='Pieza presente en boca.')),
                ('has_implant', models.BooleanField(default=False)),
                ('mobility', models.PositiveSmallIntegerField(default=0, help_text='Grado 0 a 3.')),
                ('furcation_buccal', models.PositiveSmallIntegerField(default=0, help_text='Grado 0 a 3.')),
                ('furcation_lingual', models.PositiveSmallIntegerField(default=0)),
                ('gum_width', models.PositiveSmallIntegerField(default=0, help_text='Ancho de encía en mm.')),
                ('probing_depth', models.JSONField(blank=True, default=list, help_text='6 enteros (mm).')),
                ('gingival_margin', models.JSONField(blank=True, default=list, help_text='6 enteros (mm).')),
                ('bleeding', models.JSONField(blank=True, default=list, help_text='6 booleanos.')),
                ('plaque', models.JSONField(blank=True, default=list, help_text='6 booleanos.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='clinical.periodontalexam')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Pieza del periodontograma',
                'verbose_name_plural': 'Piezas del periodontograma',
                'ordering': ['tooth_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodontaltooth',
            constraint=models.UniqueConstraint(fields=('exam', 'tooth_code'), name='unique_tooth_per_periodontal_exam'),
        ),
    ]
