# Generated by Django 6.0.6 on 2026-07-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('configuration', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='specialties.specialty'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='configuration.treatment'),
        ),
        migrations.AddConstraint(
            model_name='systemparameter',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='unique_parameter_key_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['tenant', 'specialty'], name='configurati_tenant__abcf51_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('treatment', 'agreement'), name='unique_tariff_per_treatment_agreement'),
        ),
    ]
