# Generated by Django 6.0.6 on 2026-07-07 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Insumo de tratamiento',
                'verbose_name_plural': 'Insumos de tratamiento',
            },
        ),
    ]
