# Generated by Django 6.0.6 on 2026-07-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_treatmentinventoryitem'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentinventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='treatmentinventoryitem',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='configuration.treatment'),
        ),
    ]
