# Generated by Django 5.0.9 on 2026-07-20 20:49

import apps.configuration.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_platform_v2'),
        ('configuration', '0004_treatmentinventoryitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('theme', models.JSONField(blank=True, default=apps.configuration.models._default_theme)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clinicbranding',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uniq_branding_per_tenant'),
        ),
    ]
