# Generated by Django 5.0.9 on 2026-07-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_clinicbranding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicbranding',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nombre comercial de la clínica.', max_length=120),
        ),
        migrations.AddField(
            model_name='clinicbranding',
            name='short_name',
            field=models.CharField(blank=True, help_text='Nombre corto (opcional, para espacios reducidos).', max_length=40),
        ),
    ]
