# Generated by Django 5.0.9 on 2026-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_clinicbranding_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicbranding',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de la clínica.', max_length=200),
        ),
        migrations.AddField(
            model_name='clinicbranding',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico institucional.', max_length=254),
        ),
        migrations.AddField(
            model_name='clinicbranding',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto.', max_length=40),
        ),
    ]
