# Generated by Django 5.0.9 on 2026-08-06 23:00

import apps.configuration.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_platform_v2"),
        ("configuration", "0007_clinicbranding_address_clinicbranding_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAppearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "header",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_header,
                    ),
                ),
                (
                    "footer",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_footer,
                    ),
                ),
                (
                    "typography",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_typography,
                    ),
                ),
                (
                    "palette",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_palette,
                    ),
                ),
                (
                    "tables",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_tables,
                    ),
                ),
                (
                    "page",
                    models.JSONField(
                        blank=True, default=apps.configuration.models._default_doc_page
                    ),
                ),
                (
                    "logo",
                    models.JSONField(
                        blank=True, default=apps.configuration.models._default_doc_logo
                    ),
                ),
                (
                    "signature",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_signature,
                    ),
                ),
                (
                    "watermark",
                    models.JSONField(
                        blank=True,
                        default=apps.configuration.models._default_doc_watermark,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="common.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apariencia de documentos",
                "verbose_name_plural": "Apariencia de documentos",
            },
        ),
        migrations.AddConstraint(
            model_name="documentappearance",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="uniq_docappearance_per_tenant"
            ),
        ),
    ]
