# Generated by Django 6.0.6 on 2026-07-07 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('common', '0001_initial'),
        ('patients', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('form_data', models.JSONField(default=dict, help_text='Campos específicos de la especialidad (estructura flexible).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_forms', to='agenda.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_forms', to='patients.patient')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='specialties.specialty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.tenant')),
            ],
            options={
                'verbose_name': 'Formulario de especialidad',
                'verbose_name_plural': 'Formularios de especialidad',
                'indexes': [models.Index(fields=['patient', 'specialty'], name='specialties_patient_83a62b_idx')],
            },
        ),
    ]
