# Generated by Django 6.0.6 on 2026-07-10 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('reception', 'Recepción'), ('doctor', 'Doctor'), ('auxiliary', 'Auxiliar'), ('patient', 'Paciente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Nulo SOLO para el Super Administrador (opera sobre la plataforma, no dentro de una clínica).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='common.tenant'),
        ),
    ]
