# Generated by Django 5.0.9 on 2026-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role_alter_user_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Se marca cuando la contraseña la puso otra persona: el alta de una clínica o un restablecimiento. Mientras esté marcada, la cuenta solo puede hacer una cosa: elegir su propia contraseña.",
                verbose_name="Debe cambiar la contraseña",
            ),
        ),
    ]
