# Generated by Django 5.0.9 on 2026-09-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_contrasena_temporal"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="puede_gestionar_logros",
            field=models.BooleanField(
                default=False,
                help_text="Solo para profesionales. El administrador de la clínica siempre puede; a un doctor se le concede al crearlo. Es un permiso aparte del rol porque no todos los doctores de una clínica deciden a quién se premia.",
                verbose_name="Puede gestionar rachas y logros",
            ),
        ),
    ]
