# Generated by Django 5.0.9 on 2026-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_puede_gestionar_logros"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="puede_gestionar_whatsapp",
            field=models.BooleanField(
                default=False,
                help_text="Conectar la cuenta de WhatsApp de la clínica y encender los recordatorios. El administrador siempre puede.",
                verbose_name="Puede configurar WhatsApp",
            ),
        ),
    ]
