# Generated by Django 5.0.9 on 2026-09-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_puede_gestionar_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferencias",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Preferencias de la propia persona (p. ej. usar o no el odontograma 3D). Ver apps/accounts/preferencias.py.",
            ),
        ),
    ]
